from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
import uuid
import os

from app.database import get_db
from app.models import AuditRun, Artifact, AuditStatus

router = APIRouter(prefix="/api/audits", tags=["exports"])


@router.post("/{audit_id}/export")
async def trigger_export(
    audit_id: str,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
):
    try:
        uid = uuid.UUID(audit_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid audit ID")

    result = await db.execute(select(AuditRun).where(AuditRun.id == uid))
    run = result.scalar_one_or_none()
    if not run:
        raise HTTPException(status_code=404, detail="Audit not found")

    if run.status != AuditStatus.completed:
        raise HTTPException(status_code=400, detail="Audit must be completed before exporting")

    return {"message": "Export will be generated by the worker", "audit_id": audit_id}


@router.get("/{audit_id}/exports")
async def list_exports(audit_id: str, db: AsyncSession = Depends(get_db)):
    try:
        uid = uuid.UUID(audit_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid audit ID")

    result = await db.execute(select(AuditRun).where(AuditRun.id == uid))
    run = result.scalar_one_or_none()
    if not run:
        raise HTTPException(status_code=404, detail="Audit not found")

    artifacts_result = await db.execute(
        select(Artifact).where(Artifact.audit_run_id == uid)
    )
    artifacts = artifacts_result.scalars().all()

    return {
        "items": [
            {
                "id": str(a.id),
                "artifact_type": a.artifact_type,
                "file_path": a.file_path,
                "file_size_bytes": a.file_size_bytes,
                "created_at": a.created_at.isoformat(),
            }
            for a in artifacts
        ]
    }


@router.get("/{audit_id}/exports/{artifact_id}/download")
async def download_artifact(
    audit_id: str,
    artifact_id: str,
    db: AsyncSession = Depends(get_db),
):
    try:
        audit_uid = uuid.UUID(audit_id)
        artifact_uid = uuid.UUID(artifact_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid ID")

    result = await db.execute(
        select(Artifact)
        .where(Artifact.id == artifact_uid)
        .where(Artifact.audit_run_id == audit_uid)
    )
    artifact = result.scalar_one_or_none()
    if not artifact:
        raise HTTPException(status_code=404, detail="Artifact not found")

    if not os.path.exists(artifact.file_path):
        raise HTTPException(status_code=404, detail="Artifact file not found on disk")

    return FileResponse(
        path=artifact.file_path,
        filename=os.path.basename(artifact.file_path),
        media_type="application/octet-stream",
    )
